<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <UserSecretsId>94c24cba-f03f-4453-a671-3640b517c573</UserSecretsId>
    <!-- x-release-please-start-version -->
    <Version>1.6.1</Version>
    <AssemblyVersion>1.6.1</AssemblyVersion>
    <!-- x-release-please-end -->
    <AssemblyName>AdbClient.Web</AssemblyName>
    <RootNamespace>AdbClient.Web</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="service-install.bat" />
    <None Remove="service-firewall.ps1" />
    <None Remove="service-remove.bat" />
    <None Remove="update.cmd" />
    <None Remove="update.ps1" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="service-install.bat">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      <CopyToPublishDirectory>Always</CopyToPublishDirectory>
    </Content>
    <Content Include="service-firewall.ps1">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      <CopyToPublishDirectory>Always</CopyToPublishDirectory>
    </Content>
    <Content Include="service-remove.bat">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      <CopyToPublishDirectory>Always</CopyToPublishDirectory>
    </Content>
    <Content Include="update.cmd">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      <CopyToPublishDirectory>Always</CopyToPublishDirectory>
    </Content>
    <Content Include="update.ps1">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      <CopyToPublishDirectory>Always</CopyToPublishDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.11" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite.Core" Version="10.0.11" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="10.0.11">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Extensions.Hosting.WindowsServices" Version="10.0.11" />
    <PackageReference Include="Serilog" Version="4.4.0" />
    <PackageReference Include="Serilog.AspNetCore" Version="10.0.0" />
    <PackageReference Include="Serilog.Sinks.File" Version="7.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\AdbClient.Data\AdbClient.Data.csproj" />
    <ProjectReference Include="..\AdbClient.Service\AdbClient.Service.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="wwwroot\" />
  </ItemGroup>


</Project>
